site_name: "Open Quantum Data Commons (openQDC)"
site_description: "I don't know... Something about data and Quantum stuff I guess :D"
repo_url: "https://github.com/OpenDrugDiscovery/openQDC"
repo_name: "openQDC"
copyright: Copyright 2023 Valence Labs

site_url: "https://github.com/OpenDrugDiscovery/openQDC"
remote_branch: "privpage"
use_directory_urls: false
docs_dir: "docs"

# Fail on warnings to detect issues with types and docstring
strict: false

nav:
  - Overview: index.md
  - Usage: usage.md
  - CLI: cli.md
  - Available Datasets: datasets.md
  - Tutorials:
    - Really hard example: tutorials/usage.ipynb
  - API:
    - Datasets:
      - Potential Energy:
        - Alchemy : API/datasets/alchemy.md
        - ANI : API/datasets/ani.md
        - Spice : API/datasets/spice.md
        - GEOM : API/datasets/geom.md
        - Qmugs : API/datasets/qmugs.md
        - ISO_17 : API/datasets/iso_17.md
        - Comp6 : API/datasets/comp6.md
        - GDML : API/datasets/gdml.md
        - Molecule3D : API/datasets/molecule3d.md
        - Orbnet Denali : API/datasets/orbnet_denali.md
        - SN2 RXN : API/datasets/sn2_rxn.md
        - QM7X : API/datasets/qm7x.md
        - QM1B : API/datasets/qm1b.md
        - NablaDFT : API/datasets/nabladft.md
        - Solvated Peptides : API/datasets/solvated_peptides.md
        - Waterclusters3_30 : API/datasets/waterclusters3_30.md
        - SCAN Waterclusters : API/datasets/waterclusters.md
        - TMQM : API/datasets/tmqm.md
        - PCQM : API/datasets/pcqm.md
        - RevMD17 : API/datasets/revmd17.md
        - MD22 : API/datasets/md22.md
        - Transition1X : API/datasets/transition1x.md
        - MultixcQM9 : API/datasets/multixcqm9.md
        - QMX : API/datasets/qmx.md
        - Protein Fragments : API/datasets/proteinfragments.md
        - VQM24 : API/datasets/vqm24.md
      - Interaction Energy:
        - DES : API/datasets/des.md
        - L7 : API/datasets/l7.md
        - X40 : API/datasets/x40.md
        - Metcalf : API/datasets/metcalf.md
        - Splinter : API/datasets/splinter.md
    - e0 and QM methods: API/methods.md
    - Units: API/units.md
    - Utils: API/utils.md
  - Contribute: contribute.md
  - Add a dataset: dataset_upload.md
  - License: licensing.md

theme:
  name: material
  custom_dir: docs/_overrides
  #palette:
  #  primary: purple
  #  accent: purple
  features:
    - navigation.tabs
    #- navigation.expand


extra_css:
  - css/custom.css
  - css/custom-openqdc.css

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  #- https://unpkg.com/mermaid@10.9.0/dist/mermaid.min.js

markdown_extensions:
  - admonition
  - markdown_include.include
  - pymdownx.emoji
  - pymdownx.highlight
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  # For `tab_length=2` in the markdown extension
  # See https://github.com/mkdocs/mkdocs/issues/545
  - mdx_truly_sane_lists
  - mkdocs-click
  - attr_list
  - md_in_html
  - toc:
      permalink: true

watch:
  - openqdc/

plugins:
  - search
  - mkdocstrings:
      #watch:
      #  - openqdc/
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append("docs")
            - sys.path.append("openqdc")
          selection:
            new_path_syntax: yes
          rendering:
            show_root_heading: yes
            heading_level: 3
            show_if_no_docstring: false
  - mkdocs-jupyter:
      execute: False
      # kernel_name: python3

extra:
  version:
    provider: mike
